# Deploy static HTML/CSS site to Azure Web App

name: Deploy Static Website to Azure Web App - Nithishloginpage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0BA61CEA411E46138594975CE8D90783 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_57CC6F97EB854304B162F6B1FDDBF820 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AE864BA04E6041DBA9D79D321D4389DA }}

      # 3. Deploy files to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Nithishloginpage'
          slot-name: 'Production'
          package: .
